<?php

declare(strict_types=1);

namespace App\Modules\Core\Seo\StructuredData;

use App\Modules\Core\Contracts\SiteSeoDefaultsContract;
use App\Modules\Core\Seo\ResolvedSeo;
use Illuminate\Database\Eloquent\Model;
use LogicException;

/**
 * JSON-LD for public content (ADR 0058 §5).
 *
 * The backend builds it because the backend composes the absolute addresses it names; the
 * frontend places it in the page. Every text value is plain text — markup is stripped — so a
 * title cannot close the script element JSON-LD is embedded in. Empty values are left out
 * rather than published as nulls.
 */
final class StructuredData
{
    public const CONTEXT = 'https://schema.org';

    /** @var array<string, StructuredDataGenerator> */
    private array $generators = [];

    public function register(StructuredDataGenerator $generator): void
    {
        $key = $generator->key();
        $existing = $this->generators[$key] ?? null;

        if ($existing !== null && $existing::class !== $generator::class) {
            throw new LogicException("Structured data for [{$key}] is already generated by ".$existing::class.'.');
        }

        $this->generators[$key] = $generator;
    }

    public function has(string $key): bool
    {
        return isset($this->generators[$key]);
    }

    /**
     * The site's `WebSite` and `Organization`, in one language.
     *
     * @return list<array<string, mixed>>
     */
    public function siteNodes(string $locale): array
    {
        $defaults = app(SiteSeoDefaultsContract::class);
        $origin = $defaults->publicOrigin();
        $origin = $origin === null ? null : rtrim($origin, '/');
        $name = $defaults->title($locale);

        return [
            self::clean([
                '@type' => 'WebSite',
                '@id' => $origin === null ? null : $origin.'/#website',
                'url' => $origin === null ? null : $origin.'/',
                'name' => $name,
                'description' => $defaults->description($locale),
                'inLanguage' => $locale,
                'publisher' => $origin === null ? null : ['@id' => $origin.'/#organization'],
            ]),
            self::clean([
                '@type' => 'Organization',
                '@id' => $origin === null ? null : $origin.'/#organization',
                'url' => $origin === null ? null : $origin.'/',
                'name' => $name,
            ]),
        ];
    }

    /**
     * The graph for one piece of content, or null when no generator describes its type.
     *
     * @return array{'@context': string, '@graph': list<array<string, mixed>>}|null
     */
    public function for(string $key, Model $owner, string $locale, ResolvedSeo $seo, ?string $url): ?array
    {
        $generator = $this->generators[$key] ?? null;

        if ($generator === null) {
            return null;
        }

        $site = $this->siteNodes($locale);
        $node = $generator->node($owner, $locale, $seo, $url);
        $website = $site[0]['@id'] ?? null;

        if (is_string($website) && ! isset($node['isPartOf'])) {
            $node['isPartOf'] = ['@id' => $website];
        }

        return ['@context' => self::CONTEXT, '@graph' => [...$site, self::clean($node)]];
    }

    /** Plain text: markup stripped, whitespace collapsed, empty as null. */
    public static function text(?string $value): ?string
    {
        if ($value === null) {
            return null;
        }

        $text = trim((string) preg_replace('/\s+/u', ' ', strip_tags($value)));

        return $text === '' ? null : $text;
    }

    /**
     * Drops nulls and empty lists, recursively, and makes every string plain text.
     *
     * @param  array<array-key, mixed>  $node
     * @return array<array-key, mixed>
     */
    public static function clean(array $node): array
    {
        $clean = [];

        foreach ($node as $key => $value) {
            if (is_string($value)) {
                $value = self::text($value);
            } elseif (is_array($value)) {
                $value = self::clean($value);
            }

            if ($value === null || $value === []) {
                continue;
            }

            $clean[$key] = $value;
        }

        return array_is_list($node) ? array_values($clean) : $clean;
    }
}
