<?php

declare(strict_types=1);

namespace App\Modules\Auth\Services;

use App\Modules\Auth\Data\SocialSignIn;
use App\Modules\Auth\Exceptions\SocialLoginException;
use App\Modules\Core\Audit\AuditAction;
use App\Modules\Core\Cache\CacheNamespace;
use App\Modules\Core\Contracts\AuditRecorderContract;
use App\Modules\Core\Contracts\PlatformCacheContract;
use App\Modules\Core\Support\ClientUrlPolicy;
use App\Modules\Integration\Contracts\SocialLoginGatewayContract;
use App\Modules\Integration\Data\SocialAuthorizationRequest;
use App\Modules\Integration\Data\SocialCodeExchange;
use App\Modules\Integration\Data\SocialProfile;
use App\Modules\Integration\Exceptions\SocialProviderException;
use App\Modules\Integration\Exceptions\SocialProviderUnavailableException;
use App\Modules\User\Contracts\SocialIdentityRegistryContract;
use App\Modules\User\Data\SocialIdentityLink;
use App\Modules\User\Exceptions\SocialIdentityException;
use App\Modules\User\Models\User;
use Illuminate\Database\UniqueConstraintViolationException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Social login for user accounts, end to end (ADR 0050).
 *
 * ## The order is the security
 *
 * A callback is decided in a fixed sequence, and each step runs only if the one before it
 * passed: the state is consumed, the PKCE verifier is checked against it, the code is
 * redeemed and the ID token validated, and only then is anything looked up. Nothing the
 * client sends names an account or an identity — the subject comes from a token the
 * provider signed, and the redirect URI and nonce come from the stored state.
 *
 * ## State is single-use, and the client is bound to it
 *
 * The state is stored under a hash of its value in the fail-closed AUTH namespace and is
 * consumed atomically: the first request to claim it wins, and a replay — even one racing
 * the original — loses. Consuming it spends it whatever happens next, so a wrong verifier
 * cannot be retried against the same state.
 *
 * The PKCE verifier is generated by the client and never leaves it until the callback.
 * Checking it here, before the code is redeemed, is what stops a victim's client being
 * made to finish an attacker's sign-in.
 *
 * ## No account is ever matched by address
 *
 * An address the provider reports is compared against accounts for two purposes only: to
 * refuse outright when it belongs to an administrator, whatever the provider says about
 * it, and to refuse with `SOCIAL_IDENTITY_NOT_LINKED` when it belongs to a user — who
 * signs in by an existing method and links explicitly. It never links anything.
 *
 * Provider verification decides this flow and nothing else. It is not local verification,
 * and nothing here writes `email_verified_at`.
 */
class SocialLoginFlow
{
    public const INTENT_SIGN_IN = 'sign_in';

    public const INTENT_LINK = 'link';

    /**
     * How long an authorization stays redeemable.
     */
    public const STATE_TTL_SECONDS = 600;

    private const STATE_RESOURCE = 'social_state';

    private const CONSUMED_RESOURCE = 'social_state_consumed';

    public function __construct(
        private readonly SocialLoginGatewayContract $gateway,
        private readonly PlatformCacheContract $cache,
        private readonly SocialIdentityRegistryContract $identities,
        private readonly AuditRecorderContract $audit,
        private readonly PasswordRecoveryService $recovery,
    ) {}

    /**
     * Whether the platform offers social login at all. Off until an operator says so.
     */
    public function isEnabled(): bool
    {
        return setting('auth.social_login_enabled', false) === true;
    }

    /**
     * The providers a client may offer. Empty while social login is off.
     *
     * @return array<int, array{key: string, label: string}>
     */
    public function providers(): array
    {
        // A provider is offered only when a sign-in through it could actually start: the
        // switch is on, the provider is effective, and at least one return address is
        // usable in this environment. Anything less offers a button that always fails.
        if (! $this->isEnabled()) {
            return [];
        }

        $usable = array_filter($this->redirectUris(), static fn (array $entry): bool => $entry['problem'] === null);

        return $usable === [] ? [] : $this->gateway->availableProviders();
    }

    /**
     * Begin a sign-in or a link: store the state, and return where to send the person.
     *
     * @return array{authorization_url: string, expires_at: string}
     *
     * @throws SocialLoginException
     */
    public function authorize(string $provider, string $redirectUri, string $codeChallenge, string $intent, ?User $user = null): array
    {
        if (! $this->isEnabled() || ! $this->gateway->isAvailable($provider)) {
            throw SocialLoginException::providerUnavailable();
        }

        if ($intent === self::INTENT_LINK && ($user === null || $user->isAdmin())) {
            if ($user !== null) {
                $this->recordAdministratorRefusal($provider, $user->id, SocialLoginException::ADMIN_ACCOUNT);
            }

            throw SocialLoginException::refused(SocialLoginException::ADMIN_ACCOUNT);
        }

        if (! $this->redirectUriAllowed($redirectUri)) {
            throw SocialLoginException::invalidRedirectUri();
        }

        $state = bin2hex(random_bytes(32));
        $nonce = bin2hex(random_bytes(32));

        try {
            $url = $this->gateway->authorizationUrl(
                $provider,
                new SocialAuthorizationRequest($redirectUri, $state, $nonce, $codeChallenge)
            );
        } catch (SocialProviderUnavailableException) {
            throw SocialLoginException::providerUnavailable();
        }

        $this->cache->put(CacheNamespace::AUTH, self::STATE_RESOURCE, [hash('sha256', $state)], [
            'provider' => $provider,
            'intent' => $intent,
            'redirect_uri' => $redirectUri,
            'code_challenge' => $codeChallenge,
            'nonce' => $nonce,
            'user_id' => $user?->id,
        ], self::STATE_TTL_SECONDS);

        return [
            'authorization_url' => $url,
            'expires_at' => now()->addSeconds(self::STATE_TTL_SECONDS)->toIso8601String(),
        ];
    }

    /**
     * Finish a sign-in, in the order ADR 0050 §3 fixes.
     *
     * @throws SocialLoginException
     */
    public function signIn(string $provider, string $code, string $state, string $codeVerifier): SocialSignIn
    {
        if (! $this->isEnabled()) {
            throw SocialLoginException::providerUnavailable();
        }

        $stored = $this->consumeState($provider, $state, $codeVerifier, self::INTENT_SIGN_IN, null);
        $profile = $this->exchange($provider, $code, $codeVerifier, $stored);

        $identity = $this->identities->findBySubject($provider, $profile->subject);

        if ($identity !== null) {
            // A subject unlinked from its account stays reserved to it. It signs nobody
            // in and creates nothing; only that account can link it again.
            if (! $identity->isLinked()) {
                throw SocialLoginException::refused(SocialLoginException::UNLINKED_IDENTITY);
            }

            $user = User::query()->find($identity->user_id);

            if ($user === null) {
                throw SocialLoginException::refused(SocialLoginException::UNLINKED_IDENTITY);
            }

            // Unreachable: the database refuses a linked identity on an administrator.
            // Checked anyway, because this is the step that would otherwise mint a token.
            if ($user->isAdmin()) {
                $this->recordAdministratorRefusal($provider, $user->id, SocialLoginException::ADMIN_ACCOUNT);

                throw SocialLoginException::refused(SocialLoginException::ADMIN_ACCOUNT);
            }

            if (! $user->is_active) {
                throw SocialLoginException::refused(SocialLoginException::INACTIVE_ACCOUNT);
            }

            $this->identities->recordUse($identity);

            return new SocialSignIn($user, created: false);
        }

        $email = $this->normaliseEmail($profile->email);

        // Compared without regard to case, whatever case an account's address was stored
        // in: the administrator refusal cannot be dodged by capitalisation.
        $match = $email === null
            ? null
            : User::query()->whereRaw('lower(email) = ?', [$email])->first();

        // Before any other address rule, and whether or not the provider vouches for the
        // address: an administrator's address is never matched against.
        if ($match !== null && $match->isAdmin()) {
            $this->recordAdministratorRefusal($provider, $match->id, SocialLoginException::ADMIN_EMAIL_MATCH);

            throw SocialLoginException::refused(SocialLoginException::ADMIN_EMAIL_MATCH);
        }

        if ($email === null || ! $profile->emailVerified) {
            throw SocialLoginException::refused(SocialLoginException::UNVERIFIED_EMAIL);
        }

        if ($match !== null) {
            throw SocialLoginException::identityNotLinked();
        }

        if (setting('auth.registration_enabled', false) !== true) {
            throw SocialLoginException::registrationClosed();
        }

        // An account created here has no password, so recovery by email is its only way
        // back in if the provider is ever lost (ADR 0050 §12). In production that way back
        // has to exist before such an account may be created.
        if (app()->isProduction() && $this->recovery->resetPageUrl() === null) {
            Log::warning('Social registration was refused because auth.password_reset_url is not usable in production.');

            throw SocialLoginException::registrationClosed();
        }

        return new SocialSignIn($this->register($provider, $profile, $email), created: true);
    }

    /**
     * Finish linking a provider to the signed-in account.
     *
     * No address rule applies: the holder is signed in and is linking this identity to
     * this account on purpose, which is the explicit link ADR 0050 §5 asks for.
     *
     * @throws SocialLoginException
     * @throws SocialIdentityException
     */
    public function link(User $user, string $provider, string $code, string $state, string $codeVerifier): SocialIdentityLink
    {
        if (! $this->isEnabled()) {
            throw SocialLoginException::providerUnavailable();
        }

        $stored = $this->consumeState($provider, $state, $codeVerifier, self::INTENT_LINK, $user);
        $profile = $this->exchange($provider, $code, $codeVerifier, $stored);

        try {
            return $this->identities->link($user, $provider, $profile->subject, $this->normaliseEmail($profile->email));
        } catch (SocialIdentityException $e) {
            if ($e->reason === SocialIdentityException::ADMINISTRATOR) {
                $this->recordAdministratorRefusal($provider, $user->id, SocialLoginException::ADMIN_ACCOUNT);
            }

            throw $e;
        }
    }

    /**
     * Claim the state exactly once, and prove the caller is the client that started the
     * flow.
     *
     * @return array{provider: string, intent: string, redirect_uri: string, code_challenge: string, nonce: string, user_id: string|null}
     *
     * @throws SocialLoginException
     */
    private function consumeState(string $provider, string $state, string $codeVerifier, string $intent, ?User $user): array
    {
        $key = [hash('sha256', $state)];

        // First claim wins, atomically. A replay loses here, and so does a second request
        // racing the first with the same state.
        if (! $this->cache->add(CacheNamespace::AUTH, self::CONSUMED_RESOURCE, $key, true, self::STATE_TTL_SECONDS)) {
            throw SocialLoginException::stateInvalid();
        }

        $stored = $this->cache->get(CacheNamespace::AUTH, self::STATE_RESOURCE, $key);
        $this->cache->forget(CacheNamespace::AUTH, self::STATE_RESOURCE, $key);

        if (! is_array($stored)
            || ($stored['provider'] ?? null) !== $provider
            || ($stored['intent'] ?? null) !== $intent
            || ($stored['user_id'] ?? null) !== $user?->id
            || ! is_string($stored['redirect_uri'] ?? null)
            || ! is_string($stored['nonce'] ?? null)
            || ! is_string($stored['code_challenge'] ?? null)) {
            throw SocialLoginException::stateInvalid();
        }

        $challenge = rtrim(strtr(base64_encode(hash('sha256', $codeVerifier, true)), '+/', '-_'), '=');

        if (! hash_equals($stored['code_challenge'], $challenge)) {
            throw SocialLoginException::stateInvalid();
        }

        return $stored;
    }

    /**
     * @param  array{redirect_uri: string, nonce: string}  $stored
     *
     * @throws SocialLoginException
     */
    private function exchange(string $provider, string $code, string $codeVerifier, array $stored): SocialProfile
    {
        try {
            return $this->gateway->exchange(
                $provider,
                new SocialCodeExchange($code, $codeVerifier, $stored['redirect_uri'], $stored['nonce'])
            );
        } catch (SocialProviderUnavailableException) {
            throw SocialLoginException::providerUnavailable();
        } catch (SocialProviderException) {
            // What failed is in the usage log, written by the gateway. The caller learns
            // only that the provider did not establish an identity.
            throw SocialLoginException::providerError();
        }
    }

    /**
     * Create the account a first social sign-in asks for (ADR 0050 §4).
     *
     * A user, always: `account_type` is not fillable and takes its default. No password,
     * because this person signs in through the provider. And `email_verified_at` is left
     * alone — the provider vouching for an address is not the platform verifying it.
     *
     * @throws SocialLoginException
     */
    private function register(string $provider, SocialProfile $profile, string $email): User
    {
        try {
            return DB::transaction(function () use ($provider, $profile, $email): User {
                $user = new User([
                    'name' => $this->displayName($profile, $email),
                    'email' => $email,
                    'password' => null,
                    'is_active' => true,
                ]);

                $user->save();

                // The account and the record of it commit together (ADR 0037).
                $this->audit->succeeded(AuditAction::ACCOUNT_CREATED, $user->id, [
                    'active' => true,
                    'source' => 'social',
                    'provider' => $provider,
                ]);

                $this->identities->link($user, $provider, $profile->subject, $email);

                return $user->refresh();
            });
        } catch (UniqueConstraintViolationException|SocialIdentityException) {
            // Another request created this account or claimed this identity in the same
            // instant. Nothing was created here, and nothing is linked by address.
            throw SocialLoginException::identityNotLinked();
        }
    }

    /**
     * Every configured return address, with what makes it unusable here, if anything.
     *
     * Judged in this environment, every time: a value saved before the environment became
     * production, or restored from a backup, is not trusted for being stored. An entry
     * listed twice is reported on its second appearance.
     *
     * @return list<array{uri: string, problem: string|null}>
     */
    public function redirectUris(): array
    {
        $configured = setting('auth.social_redirect_uris', []);

        if (! is_array($configured)) {
            return [];
        }

        $policy = ClientUrlPolicy::forCurrentEnvironment();
        $seen = [];
        $report = [];

        foreach ($configured as $candidate) {
            $problem = $policy->redirectUriProblem($candidate);
            $uri = is_string($candidate) ? $candidate : (string) json_encode($candidate);

            if ($problem === null && in_array($uri, $seen, true)) {
                $problem = 'duplicate';
            }

            $seen[] = $uri;
            $report[] = ['uri' => $uri, 'problem' => $problem];
        }

        return $report;
    }

    private function redirectUriAllowed(string $redirectUri): bool
    {
        // Exact match against a usable entry, and nothing looser. A prefix or pattern
        // match is how a redirect allowlist ends up sending a code to a path an attacker
        // controls.
        foreach ($this->redirectUris() as $entry) {
            if ($entry['problem'] === null && hash_equals($entry['uri'], $redirectUri)) {
                return true;
            }
        }

        return false;
    }

    private function normaliseEmail(?string $email): ?string
    {
        if ($email === null) {
            return null;
        }

        $trimmed = trim($email);

        return $trimmed === '' ? null : mb_strtolower($trimmed);
    }

    private function displayName(SocialProfile $profile, string $email): string
    {
        $name = $profile->name ?? strstr($email, '@', true);

        return mb_substr(is_string($name) && $name !== '' ? $name : $email, 0, 150);
    }

    /**
     * Record a social provider being used against an administrative account — one of the
     * two refusals the trail admits (ADR 0037 extension of 2026-09-13).
     */
    private function recordAdministratorRefusal(string $provider, string $accountId, string $reason): void
    {
        $this->audit->failed(AuditAction::AUTH_SOCIAL_REFUSED, $accountId, [
            'provider' => $provider,
            'reason' => $reason,
        ]);
    }
}
